services:
  nats:
    image: nats:2.10.22-alpine3.20
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats:/data
    command: >
      sh -c "
      apk add curl --no-cache &&
      curl -sf https://binaries.nats.dev/nats-io/natscli/nats@latest | sh &&
      mv nats /usr/local/bin/ &&
      nats --version &&
      nats-server --js --sd=/data --http_port 8222
      "

volumes:
  nats:
