services:
  nats:
    image: docker.io/nats:2.10.22
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats:/data
    command: --js --sd=/data --http_port 8222

volumes:
  nats:
